language: node_js
sudo: false
node_js:
- stable
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
cache:
  directories:
  - node_modules
before_script:
- npm install -g polymer-cli
- npm install -g web-component-tester-istanbul
- npm install -g bower
- npm install -g firebase-tools
- bower install
script:
- polymer test
- npm install selenium-standalone@latest -g
- selenium-standalone install
- selenium-standalone start
- npm test
after_success:
- polymer build
#- firebase deploy --project "${FIREBASE_PROJECT_VINCE}" --token "${FIREBASE_TOKEN_VINCE}"
- branch=$(git branch | sed -n -e 's/^\* \(.*\)/\1/p')
- echo $branch
- if [[ ${branch} == *"feature"* ]]; then firebase deploy --project "${FIREBASE_PROJECT_VINCE}" --token "${FIREBASE_TOKEN_VINCE}" ; fi
