language: node_js
sudo: false
node_js:
- stable
cache:
  directories:
  - node_modules
before_script:
- npm install -g polymer-cli
- npm install -g web-component-tester-istanbul
- npm install -g bower
- npm install -g firebase-tools
script:
- polymer test --webserver-port 7055
after_success:
- polymer build
- firebase --project escr-shop-dev deploy
#- STATUS=`git status`; if [[ ${STATUS} == *"feature"* ]]; then firebase deploy --email ${FIREBASE_USERNAME} --password ${FIREBASE_PASSWORD}; fi
