language: node_js
sudo: false
node_js:
- stable
before_install:
- npm install selenium-standalone@latest -g
- selenium-standalone install
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
cache:
  directories:
  - node_modules
before_script:
- npm install -g polymer-cli
- npm install -g web-component-tester-istanbul
- npm install -g bower
- npm install -g firebase-tools
- bower install
- selenium-standalone start &
script:
- polymer test
#- npm test
after_success:
- polymer build
- ./firebase_deploy.sh $FIREBASE_PROJECT_VINCE $FIREBASE_TOKEN_VINCE deploy 
