language: node_js
sudo: false
node_js:
- stable
cache:
  directories:
  - node_modules
before_script:
- npm install -g polymer-cli
- npm install -g web-component-tester-istanbul
- npm install -g bower
script:
- polymer test --plugin web-component-tester-istanbul
after_success:
- polymer build
- npm install -g firebase-tools
- firebase deploy --email ${FIREBASE_USERNAME} --password ${FIREBASE_PASSWORD}
